apiVersion: apps/v1
kind: Deployment
metadata:
  name: dendrite
  namespace: dendrite
  labels:
    app: dendrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dendrite
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dendrite
    spec:
      containers:
        - image: matrixdotorg/dendrite-monolith:v0.8.2
          name: monolith
          ports:
            - containerPort: 8008
              name: monolith
          volumeMounts:
            - mountPath: /etc/dendrite
              name: encryption-secrets
              readOnly: true
            - mountPath: /var/dendrite/media
              name: media
              readOnly: false
            - mountPath: /var/jetstream
              name: jetstream
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: encryption-secrets
          secret:
            secretName: encryption-secrets
        - name: media
          persistentVolumeClaim:
            claimName: dendrite-media
        - name: jetstream
          persistentVolumeClaim:
            claimName: dendrite-jetstream
status: {}
